---
title: "Top 10 Big 5 scorers under the lens (part 1)"
description: |
  An analysis of the top ten scorers in the big 5. Who is the goat of the scorers?!
author:
  - name: Thibault Senegas
    url: https://tsenegas.netlify.com
date: 07-21-2021
output:
  distill::distill_article:
    code_folding: true
    self_contained: false
    toc: true
    toc_depth : 2
creative_commons: CC BY    
categories:
  - sports analytics
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(dplyr)
library(ggplot2)
library(gridExtra)
library(ggpubr)

```



## Retrieve data from [FBREF](https://fbref.com/en/)

```{r retrieve data of the TOP10 scorers, message=FALSE}
library(worldfootballR)
## Lewandowski
rl9 <- fb_player_match_logs("https://fbref.com/en/players/8d78e732/Robert-Lewandowski",
                           season_end_year = 2021, stat_type = 'summary')
## Mbappe
km10 <- fb_player_match_logs("https://fbref.com/en/players/42fd9c7f/Kylian-Mbappe",
                            season_end_year = 2021, stat_type = 'summary')
## Haaland
eh9 <- fb_player_match_logs("https://fbref.com/en/players/1f44ac21/Erling-Haaland",
                           season_end_year = 2021, stat_type = 'summary')
## Messi
m10 <- fb_player_match_logs("https://fbref.com/en/players/d70ce98e/Lionel-Messi",
                            season_end_year = 2021, stat_type = 'summary')
## C. Ronaldo
cr7 <- fb_player_match_logs("https://fbref.com/en/players/dea698d9/Cristiano-Ronaldo",
                     season_end_year = 2021, stat_type = 'summary')
## Kane
hk9 <- fb_player_match_logs("https://fbref.com/en/players/21a66f6a/Harry-Kane",
                            season_end_year = 2021, stat_type = 'summary')
## André Silva
AS <- fb_player_match_logs("https://fbref.com/en/players/3effaa34/matchlogs/2020-2021/summary/Andre-Silva-Match-Logs",
                           season_end_year = 2021, stat_type = 'summary')
AS$Player <- "André Silva"
## Lukaku
RLukaku9 <- fb_player_match_logs("https://fbref.com/en/players/5eae500a/Romelu-Lukaku",
                            season_end_year = 2021, stat_type = 'summary')
## Moreno
Moreno <- fb_player_match_logs("https://fbref.com/en/players/81f0781e/Gerard-Moreno",
                            season_end_year = 2021, stat_type = 'summary')
## Benzema
KB9 <- fb_player_match_logs("https://fbref.com/en/players/70d74ece/Karim-Benzema",
                               season_end_year = 2021, stat_type = 'summary')

# Create an unique df and keep only national league games
df_forwards_national_league <- rbind(cr7, eh9, km10, hk9, KB9, rl9, m10, Moreno, RLukaku9, AS)
df_forwards_national_league <- df_forwards_national_league %>% filter(Comp == "Bundesliga" | Comp == "La Liga" | Comp == "Ligue 1" | Comp == "Premier League" | Comp == "Serie A") %>% filter(Pos != "On matchday squad, but did not play")

ranking_goals <- df_forwards_national_league %>% group_by(Player) %>% mutate(goals = sum(Gls),
                                                                             min_played = sum(Min),
                                                                             xGoals = sum(xG_Expected),
                                                                             npxGoals = sum(npxG_Expected),
                                                                             penalty_kicks = sum(PK)) 
ranking_goals <- unique(ranking_goals[c(1,40,41,42,43,44)])

```



## Leaderboard

```{r, layout="l-page"}
ranking_w_penalties <- ggplot2::ggplot(ranking_goals,
                                       aes(x=reorder(Player, goals),
                                           y=goals,
                                           color=Player)) +
  geom_bar(stat="identity", fill ="white") +
  geom_text(aes(label=goals), hjust=1.5, color="black", size=3.5) +
  ggtitle("") +
  xlab("") +
  ylab("") +
  coord_flip() +
  labs(subtitle = "including penalties") +
  theme_minimal() +
  theme(legend.position="none")

ranking_wo_penalties <- ggplot2::ggplot(ranking_goals,
                                        aes(x=reorder(Player, (goals-penalty_kicks)),
                                            y=(goals-penalty_kicks),
                                            color=Player)) +
  geom_bar(stat="identity", fill ="white") +
  geom_text(aes(label=(goals-penalty_kicks)), hjust=1.5, color="black", size=3.5) +
  ggtitle("") +
  xlab("") +
  ylab("") +
  coord_flip() +
  labs(subtitle = "without penalties") +
  theme_minimal() +
  theme(legend.position="none")

grid.arrange(
  ranking_w_penalties,
  ranking_wo_penalties, 
  nrow = 1,
  top = "Ranking of the top scorers in the big 5",
  bottom = text_grob(
  "Graphic: Thibault Senegas \n Data: fbref.com",
  size = 8,
  hjust = 1,
  x = 1
  )
)
```

## Leaderboard xG

```{r, layout="l-page"}
ranking_xG_w_penalties <- ggplot2::ggplot(ranking_goals,
                                       aes(x=reorder(Player, xGoals),
                                           y=xGoals,
                                           color=Player)) +
  geom_bar(stat="identity", fill ="white") +
  geom_text(aes(label=xGoals), hjust=1.5, color="black", size=3.5) +
  ggtitle("") +
  xlab("") +
  ylab("") +
  coord_flip() +
  labs(subtitle = "including penalties") +
  theme_minimal() +
  theme(legend.position="none")

ranking_xG_wo_penalties <- ggplot2::ggplot(ranking_goals,
                                        aes(x=reorder(Player, npxGoals),
                                            y=npxGoals,
                                            color=Player)) +
  geom_bar(stat="identity", fill ="white") +
  geom_text(aes(label=npxGoals), hjust=1.5, color="black", size=3.5) +
  ggtitle("") +
  xlab("") +
  ylab("") +
  coord_flip() +
  labs(subtitle = "without penalties") +
  theme_minimal() +
  theme(legend.position="none")

grid.arrange(
  ranking_xG_w_penalties,
  ranking_xG_wo_penalties, 
  nrow = 1,
  top = "Ranking of the top scorers in the big 5",
  bottom = text_grob(
  "Graphic: Thibault Senegas \n Data: fbref.com",
  size = 8,
  hjust = 1,
  x = 1
  )
)
```